### DISCUSSION TITLE
Database subsetting and filters

### DISCUSSION THREAD

**Discussion by wwoytenko** [GreenmaskIO/greenmask#18] [Q&A]
This discussion is created to continue about subsetting and filters raised in #17

**Comment by wwoytenko** [comment]
A short recap of #17:
* Greenmask has not supported yet database subsetting
* The subset feature is going to be released in 2024 Q2-Q3
* The **temporal solution** is `query` property usage (but it can **violate PK/FK constraint**)

Example:

```yaml
- schema: "humanresources"
  name: "employee"
  query: "select * from humanresources.employee where birthdate > '1980-01-1';"
  transformers:
    - name: "RandomDate"
      params:
        column: "modifieddate"
        max: "2024-01-21 11:32:30.385227"
        min: "2020-01-21 11:32:30.385227"
```
