### DISCUSSION TITLE
Use a mono-bucket S3 Storage for multiple database dumps

### DISCUSSION THREAD

**Discussion by flazzarini** [GreenmaskIO/greenmask#56] [General]
Hello,

Firstly, I'd like to express my appreciation for this software. The progress achieved with Greenmask is commendable, and its current state is impressive.

I'm exploring a potential use case and seeking clarification on whether Greenmask supports it or if there are alternative approaches available. Here's the scenario:

### Use Case Description

I manage a central PostgreSQL database server housing multiple databases. I aim to back up selected databases to a centralized S3 bucket using Greenmask and potentially anonymize certain data within these databases. This backup process should occur regularly, resulting in a collection of database dumps within the S3 bucket. Additionally, I plan to create READ-only access tokens on S3 so that developers from various application databases can restore specific databases to their local machines.

#### Backup / Dump Process Configuration for DB-1 (dump-db1.yaml)

```
common:
  tmp_dir: ./tmp

dump:
  pg_dump_options:
    dbname: "host=localhost port=50022 user=foobar dbname=foobar"

storage:
  s3:
    endpoint: "http://localhost:50020"
    region: "us-east-1"
    bucket: "coss-db-dumps"
    access_key_id: "full-access-token"
    secret_access_key: "xxxx"
```

#### Backup / Dump Process Configuration for DB-2 (dump-db2.yaml)

```
common:
  tmp_dir: ./tmp

dump:
  pg_dump_options:
    dbname: "host=localhost port=50022 user=foobar dbname=foobaz"

storage:
  s3:
    endpoint: "http://localhost:50020"
    region: "us-east-1"
    bucket: "coss-db-dumps"
    access_key_id: "full-access-token"
    secret_access_key: "xxxx"
```

#### Developer Configuration (developer.yaml)

```
storage:
  s3:
    endpoint: "http://localhost:50020"
    region: "us-east-1"
    bucket: "coss-db-dumps"
    access_key_id: "read-access-token"
    secret_access_key: "yyyy"
```

### Dump Process Execution

The following commands are executed regularly to generate new dumps on the S3 storage within the same bucket:

```
./greenmask --config dump-db1.yaml dump
./greenmask --config dump-db2.yaml dump
```

### User Perspective

To restore the latest dump of a particular database, a user needs to list all available dumps and select the appropriate ID. For example:

```
./greenmask --config developer.yaml list-dumps
```

Suppose a developer wishes to restore the latest dump of the 'foobaz' database. In that case, they would initiate a command like this:

```
./greenmask --config developer.yaml restore -h localhost -p 50023 -U foobar -d foobaz 1712319103281
```

### Question

Is it feasible to introduce a command that simplifies this workflow? For instance, a way to indicate that the user intends to restore the latest dump of a specific database ('foobaz' in this case)?

Thank you in advance for any suggestions on streamlining this process.

**Comment by wwoytenko** [comment]
Hi @flazzarini ! Thank you for your appreciation, we really value it!

The problem is that transformations are related to the database and the config (including connection params) has to point to the specific database. If we introduce the transformation for a multiple database in the. one config file it may complicate the user experience because we will be forced to somehow match the transformation with the specific database.

But I think we can take into account developers' experience when they just fetching the database dump from mono-bucket. In that case would be fine to be able to get the latest dump for a database name provided.

Assuming we have `storage.s3.prefix` config parameter we could develop this into a kind of feature. By applying it you can at least isolate the backups for various databases in mono-bucket. 

The config for the dump might be

**Config for foobar**

```yaml
common:
  tmp_dir: ./tmp

dump:
  pg_dump_options:
    dbname: "host=localhost port=50022 user=foobar dbname=foobaz"

storage:
  s3:
    prefix: "foobar"
    endpoint: "http://localhost:50020"
    region: "us-east-1"
    bucket: "coss-db-dumps"
    access_key_id: "full-access-token"
    secret_access_key: "xxxx"
```

By applying `prefix` you can successfully use the `latest` keyword without fear that there is an unexpected database.

The next obstacle is - how to simplify the config file usage experience. Where we need only one config file and a specific database restoration request.

I suspect we could introduce the parameter `--storage-s3-prefix` that could be used for setting up the `storage.s3.prefix` parameter in the config allowing the developer to use the next call restoring dump for both databases using `latest` keyword.


`./greenmask --config developer.yaml restore --storage-s3-prefix='foobaz' -h localhost -p 50023 -U foobar -d foobaz latest`

What do you think about it? 

Feel free to share your ideas, concerns and doubts about implementation.
