### ISSUE TITLE
permission denied for large object during dump action

### ISSUE THREAD

**Issue by TCY16** [GreenmaskIO/greenmask#114]
Hi! While trying out version 1.14 I've ran into a runtime issue while trying to dump a small table. I do have output for the run, but I imagine it's not complete because of the error. I may have missed some documentation but I was hoping if you could give me some guidance.

The error is: `cannot make a backup error="data stage dumping error: at least one worker exited with error: error opening large object 75897: ERROR: permission denied for large object 75897 (SQLSTATE 42501)"`

My used config is:
```
dump:
  pg_dump_options:
    dbname: "host=obfuscated-amazon-address user=postgres dbname=db_name"
    jobs: 10
    table: "tablename"
storage:
  type: "directory"
  directory:
    path: "/home/ssm-user/tmp"
```

For completeness; The uname -r output gives: 6.1.79-99.167.amzn2023.x86_64. I've used greenmask-linux-amd64.tar.gz and the following libraries postgresql15 postgresql15-contrib. The database version is Postgres 15 as well.
