### ISSUE TITLE
feat: Set min and max values not required for int values

### ISSUE THREAD

**Issue by wwoytenko** [GreenmaskIO/greenmask#116]
Unset the required flag on `min` and `max` params so users can generate values in the min and max limit of type.

For instance 

```yaml
        - name: "RandomInt"
          params:
            column: "id"
            min: 1
```

In that case, if column `id` is int4 then the min value is 1 and the max value will be 2,147,483,647
