### ISSUE TITLE
Data Generator Request: RandomCity

### ISSUE THREAD

**Issue by jensenbox** [GreenmaskIO/greenmask#144]
I know you call them transformers but for some reason in my mind they just seem closer to data generators than something that transforms :)

Anyway, I am working on a table that has the address broken up like:

        address_line_1 character varying(1024),
        address_line_2 character varying(1024),
        city character varying(255),
        postal_code character varying(20),
        region character varying(255),
        country character varying(2),

I can use RealAddress for the address_line_1 and random data for the others but it would be nice to have `city` be something interesting.

**Comment by wwoytenko** [comment]
> I know you call them transformers but for some reason in my mind, they just seem closer to data generators than something that transforms :)

Hi! Thank your feedback. I will consider the naming, but both namings are controversial, so 
we need to choose the user-friendly. Maybe I will raise a vote in the future)

I named it transformer because some transformer changes original data rather than generate new ones. For instance, in the [latest beta](https://github.com/GreenmaskIO/greenmask/releases/tag/v0.2.0b1), you can generate [random email](https://greenmask.io/v0.2.0b1/built_in_transformers/standard_transformers/random_email/) and keeping part of email as was in original value:

```
- schema: "public"
  name: "account"
  transformers:
    - name: "RandomEmail"
      params:
        column: "email"
        engine: "hash"
        keep_original_domain: true
        local_part_template: "{{ first_name | lower }}.{{ last_name | lower }}.{{ .random_string | trunc 10 }}"
```

**Comment by wwoytenko** [comment]
> I can use RealAddress for the address_line_1 and random data for the others but it would be nice to have city be something interesting.

Good note, agree. I will try to make the RealAddress generate for useful according to your feedback.

Well I have an Idea when people can provide their own addresses or any other databases with data, for instance in json representation. The Greenmask would use that data for mapping to the columns. For instance.

```yaml
- schema: "public"
  name: "account_address"
  transformers:
    - name: "RandomDataFromFile"
      params:
        file: "/path/to/your/db.json"
        columns:
          - name: "address_line_1"
            value: "{{ db.address_line1 }}"
          - name: "city"
            value: "{{ db.city }}"
......
```

And in the file might be kind of

```json
[
 {
   "address_line_1": "val1",
   "address_line_2": "val2",
   "city": "val3",
   "postal_code": "val4",
   "region": "val5",
   "country": "val6",
 }
]
```

Why this way? I think this might be used not only for address but for multipurpose. Allowing users to define their own functional dependencies between attribute in the database provided.
