### ISSUE TITLE
Restrict which rows are dumped?

### ISSUE THREAD

**Issue by gregwebs** [GreenmaskIO/greenmask#17]
Is it possible to conditionally dump rows?

https://github.com/datanymizer/datanymizer?tab=readme-ov-file#transform-conditions-and-limit

Have you considered creating a Discussions section where questions like these could be asked?

**Comment by wwoytenko** [comment]
Hi! 
Thank you for your question. I will open discussions in a few minutes. We can raise this conversation in discussion if you want.

About your question. For now, greenmask does not support conditions for data dumping especially if we are talking about table dependencies introspected by PK references. We are working on database subsetting and it is going to be published 2024 Q2-Q3. So it will solve your problem, but not now.

But now you can **override the query** for the table:

```yaml
- schema: "humanresources"
  name: "employee"
  query: "select * from humanresources.employee where birthdate > '1980-01-1';"
  transformers:
    - name: "RandomDate"
      params:
        column: "modifieddate"
        max: "2024-01-21 11:32:30.385227"
      dynamic_params:
        min:
          column: "birthdate"
```
