### ISSUE TITLE
Dumping / Restoring fails when masking tables with a generated column.

### ISSUE THREAD

**Issue by vinnyjth** [GreenmaskIO/greenmask#183]
Steps to reproduce: 

1. Create a table with a generated column:
```

create database greenmask_test;

CREATE TABLE people (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    generated text GENERATED ALWAYS AS (id || first_name) STORED,
    first_name text
);

INSERT INTO "public"."people"("first_name") VALUES('bob') RETURNING "id", "generated", "first_name";

```
2. Mask one of the columns in the table
```
storage:
  type: "directory"
  directory:
    path: "./dump"
dump:
  pg_dump_options:
    dbname: "host=localhost port=5432 dbname=greenmask_test user=vincent password=None"
  transformation:
    - schema: public
      name: "people"
      transformers:
        - name: "Masking"
          params:
            column: "first_name"
            type: "name"
restore:
  pg_restore_options:
    dbname: "host=localhost port=5432 dbname=greenmask_final user=vincent password=None"
    disable-triggers: true
    verbose: true
```
3. Dump and restore
```
../greenmask/greenmask dump --config=./config.yml
../greenmask/greenmask restore latest --config=./config.yml
```

I see the following output in my CLI: 

```
2024-08-27T10:13:43-04:00 INF stderr forwarding Executable=pg_restore Stderr="pg_restore: warning: errors ignored on restore: 2"
2024-08-27T10:13:43-04:00 WRN unable to restore table error="error post streaming handling: error from postgres connection: extra data after last expected column  (code 22P04)"
2024-08-27T10:13:43-04:00 INF stderr forwarding Executable=pg_restore Stderr="pg_restore: connecting to database for restore"
```

I also noticed that the dump files for my table have an extra tab at the end of each line. (hard to showcase in github) 

![CleanShot 2024-08-27 at 10 19 19@2x](https://github.com/user-attachments/assets/6da7a340-8dfe-40f2-80bc-29f41197c2ba)

I tracked the bug down to [this funtion](https://github.com/GreenmaskIO/greenmask/blob/80cb1cca7d7ac941a9134ea337e1ac87b96a54c8/internal/db/postgres/pgcopy/row.go#L149-L171). It appears that the `encode` function referencing the number of columns in the DB doesn't take into generated columns. 

I've patched on my end by [completely ignoring generated columns.](https://github.com/ApollosProject/greenmask/pull/1/files#diff-c26eb11075b87d896db5bb4f94a7bd2330d342d386421456dd6a8d8044817938R270-R272). If you like that route, I'll submit a PR, but I'm guessing there's a better fix :)
