### ISSUE TITLE
S3 error when using restore "latest"

### ISSUE THREAD

**Issue by Rodeoclash** [GreenmaskIO/greenmask#195]
This might be a misunderstanding of how to use the "latest" option when picking a restore but I seem to be getting an error:

```bash
2024-09-03T23:09:27Z DBG ../../var/lib/greenmask/internal/storages/s3/logger.go:33 > s3 storage logging 0="DEBUG: Validate Response s3/ListObjectsV2 failed, attempt 0/3, error NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: JNKPMQ2SXY1EFK7A, host id: xtVfJ24FVGESi/syvq52Y1axciGENVEbbnP6bIH0It/+5pillpP6S8TbfIU/UMNK49/OIJC/HXY=" pid=1
2024-09-03T23:09:27Z FTL ../../var/lib/greenmask/cmd/greenmask/cmd/restore/restore.go:82 > cannot walk through directory error="error listing s3 objects v2: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: JNKPMQ2SXY1EFK7A, host id: xtVfJ24FVGESi/syvq52Y1axciGENVEbbnP6bIH0It/+5pillpP6S8TbfIU/UMNK49/OIJC/HXY=" pid=1
```

I've configured the IAM user to have full permissions on the bucket and its contents.

I'm invoking the command as:

```bash
greenmask --log-level debug --config /config/production.yml restore latest
```

Funnily enough, if I specify an exact version to restore, e.g.

```bash
greenmask --log-level verbose --config /config/production.yml restore 1725391129231
```

It all works great!

The config is:

```yaml
storage:
  type: "s3"
  s3:
    endpoint: "ss-apps-production-xonboard-db-backups.s3.amazonaws.com"
    bucket: "ss-apps-production-xonboard-db-backups"
    region: "ap-southeast-2"
    prefix: "super_api"

restore:
  pg_restore_options:
    dbname: "host=postgres user=postgres password=postgres dbname=super_api_dev"
    jobs: 10
```

With the S3 credentials being supplied using environment variables. The poilicy on the bucket itself for that IAM user:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:*"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::ss-apps-production-xonboard-db-backups/*",
                "arn:aws:s3:::ss-apps-production-xonboard-db-backups"
            ]
        }
    ]
}
```

I would have assumed user error had not restoring a specific version worked. If I had to guess, it looks like some weirdness with the way it's trying to traverse the bucket contents to determine the latest record 🤔
