### ISSUE TITLE
feat: Advanced subset: Polymorphic relationships

### ISSUE THREAD

**Issue by wwoytenko** [GreenmaskIO/greenmask#198]
Need to support Polymorphic relationships between tables. For instance

* kind TEXT - type of the table
* kind_id INT - FK value for a table

**Comment by wwoytenko** [comment]
Implemented. Now greenmask supports polymorphic virtual references. 

Example:

```
dump:
  virtual_references:
    - schema: "public"
      name: "comments"
      references:
        - schema: "public"
          name: "videos"
          polymorphic_exprs:
            - "public.comments.commentable_type = 'video'"
          columns:
            - name: "commentable_id"
        - schema: "public"
          name: "posts"
          polymorphic_exprs:
            - "public.comments.commentable_type = 'post'"
          columns:
            - name: "commentable_id"
```
