### ISSUE TITLE
Specify the primary key of the referenced table in a virtual reference

### ISSUE THREAD

**Issue by mikfreedman** [GreenmaskIO/greenmask#270]
Users should be able to specify the primary key of the referenced table in a virtual reference so that they can handle non-standard relationships in greenmask. 

The docs currently state that:

> You do not need to define primary key of the referenced table. Greenmask will automatically resolve it and use it in the join condition.

from [database_subset.md](https://github.com/GreenmaskIO/greenmask/blob/main/docs/database_subset.md#database-subset).

**Comment by mikfreedman** [comment]
Here is a sample schema that illustrates the challenge:

```SQL
CREATE TABLE legacy_accounts (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE accounts (
    id SERIAL PRIMARY KEY,
    legacy_id,
    username TEXT NOT NULL
);

-- Insert sample data
INSERT INTO legacy_accounts (name) VALUES
('Legacy User 1'),
('Legacy User 2'),
('Legacy User 3');

INSERT INTO accounts (legacy_id, username) VALUES
(1, 'user1'),
(2, 'user2'),
(NULL, 'user3'); -- Account without a legacy reference

```

**Comment by mikfreedman** [comment]
Here is a sample config.yml, note a new key called `referenced_table_id`

```yaml
common:
  pg_bin_path: "/usr/bin/"
  tmp_dir: "/tmp"

log:
  level: "debug"
  format: "text"

storage:
  directory:
    path: "/tmp/pg_dump_test"

dump:
  pg_dump_options:
    jobs: 10
    exclude-schema: '("teSt"*|test*)'
    load-via-partition-root: true
  virtual_references:
    - schema: "public"
      name: "legacy_accounts"
      references:
        - schema: "public"
          name: "accounts"
          columns:
            - name: "id" # the primary key on the table
           referenced_table_id: "legacy_id" # the field on the accounts table to reference rather than its id column
          not_null: true
  transformation:
    - schema: "public"
      name: "accounts"
      subset_conds:
        - "public.accounts.id = 1"
```

This config should constrain the `legacy_accounts` table and only return the first row with ID `100`
