### ISSUE TITLE
bug: `apply_for_references` cannot be combined with `when`

### ISSUE THREAD

**Issue by floriandejonckheere** [GreenmaskIO/greenmask#296]
When a transformation has both the `apply_for_references` option, and the `when` option, the latter is not applied on the referenced columns. Concretely, we have a record where we need to skip the transformation on the primary key once (because it's a magic value hardcoded in our application), but the referential integrity needs to be intact for this record and the others.

Given the following database:

```sql
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE public.users
(
    id              uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    username        character varying                      NOT NULL
);

ALTER TABLE public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

CREATE TABLE public.posts
(
    id              uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    title           character varying                      NOT NULL,
    user_id         uuid                                   NOT NULL,
    CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
);

ALTER TABLE public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);

INSERT INTO public.users (id, username)
VALUES ('4a6ea148-076b-4eb0-985b-390cf49e8338', 'admin');

INSERT INTO public.posts (title, user_id)
VALUES ('Hello World', '4a6ea148-076b-4eb0-985b-390cf49e8338');


INSERT INTO public.users (username)
VALUES ('user');

INSERT INTO public.posts (title, user_id)
VALUES ('Hello World', (SELECT id FROM users WHERE username = 'user'));
```

And the following configuration file:

```yml
---
storage:
  type: directory
  directory:
    path: "/tmp/"
dump:
  transformation:
    - schema: public
      name: users
      transformers:
        - name: RandomUuid
          apply_for_references: true
          when: raw_record.id != '4a6ea148-076b-4eb0-985b-390cf49e8338'
          params:
            column: id
            engine: hash
            keep_null: true
        - name: RandomUsername
          when: raw_record.id != '4a6ea148-076b-4eb0-985b-390cf49e8338'
          params:
            column: username
            keep_null: true
```

Greenmask will transform all `id` values in the `users` table, except for the magic one. However, in the referenced `posts` table, it will transform all `user_id` values unconditionally:

```
	"public"."users"
+-----------+----------+--------------------------------------+--------------------------------------+
| %LineNum% | Column   | OriginalValue                        | TransformedValue                     |
+-----------+----------+--------------------------------------+--------------------------------------+
| 0         | id       | 4a6ea148-076b-4eb0-985b-390cf49e8338 | 4a6ea148-076b-4eb0-985b-390cf49e8338 |
+           +----------+--------------------------------------+--------------------------------------+
|           | username | admin                                | admin                                |
+-----------+----------+--------------------------------------+--------------------------------------+
| 1         | id       | 694a5f41-9b8a-429e-ab44-0687d7867c89 | 6c23c225-908c-9b30-55ca-494957e9e0ca |
+           +----------+--------------------------------------+--------------------------------------+
|           | username | user                                 | lKDjPQP                              |
+-----------+----------+--------------------------------------+--------------------------------------+


	"public"."posts"
+-----------+---------+--------------------------------------+--------------------------------------+
| %LineNum% | Column  | OriginalValue                        | TransformedValue                     |
+-----------+---------+--------------------------------------+--------------------------------------+
| 0         | id      | faf01722-6f59-447f-87e9-2cd400f79b03 | faf01722-6f59-447f-87e9-2cd400f79b03 |
+           +---------+--------------------------------------+--------------------------------------+
|           | title   | Hello World                          | Hello World                          |
+           +---------+--------------------------------------+--------------------------------------+
|           | user_id | 4a6ea148-076b-4eb0-985b-390cf49e8338 | f5e61618-5cd7-073d-6f86-383928260abd |
+-----------+---------+--------------------------------------+--------------------------------------+
| 1         | id      | 4fead0de-fe71-4281-8e68-26eabaade9b3 | 4fead0de-fe71-4281-8e68-26eabaade9b3 |
+           +---------+--------------------------------------+--------------------------------------+
|           | title   | Hello World                          | Hello World                          |
+           +---------+--------------------------------------+--------------------------------------+
|           | user_id | 694a5f41-9b8a-429e-ab44-0687d7867c89 | 6c23c225-908c-9b30-55ca-494957e9e0ca |
+-----------+---------+--------------------------------------+--------------------------------------+
```

The result is that a restore will fail for the `posts` records that reference the user with the magic value.

I did find a workaround by defining a transformation on the referenced tables:

```yml
    - schema: public
      name: posts
      transformers:
        - name: RandomUuid
          when: raw_record.user_id != '4a6ea148-076b-4eb0-985b-390cf49e8338'
          params:
            column: user_id
            engine: hash
            keep_null: true
```
