### ISSUE TITLE
bug: wrong truncation part value

### ISSUE THREAD

**Issue by floriandejonckheere** [GreenmaskIO/greenmask#297]
When using the following configuration:

```yml
    - name: NoiseDate
      params:
        column: created_at
        max_ratio: '00:00:00.001'
        truncate: minute
```

The tool gives the error "wrong truncation part value", because `minute` is not in the allowed values. According to [the documentation](https://docs.greenmask.io/latest/built_in_transformers/standard_transformers/noise_date/#parameters), `minute` should be a valid option.

```
2025-04-22T17:41:53Z ERR ValidationWarning={"hash":"9aeb7e8b5502ad271e16be73c97f9478","meta":{"AllowedValues":["year","month","day","hour","second","millisecond","microsecond","nanosecond"],"ParameterName":"truncate","ParameterValue":"minute","SchemaName":"public","TableName":"patients","TransformerName":"NoiseDate"},"msg":"wrong truncation part value","severity":"error"}
```
