### ISSUE TITLE
Transformation conditions bug

### ISSUE THREAD

**Issue by wwoytenko** [GreenmaskIO/greenmask#301]
A was reported by @rksajib067

The forlowing config

```
       - name: "RandomEmail"
          when: "!(users.email endsWith('@xyz.com'))"
          params:
            column: "email"
            engine: "hash"
            keep_null: false
            keep_original_domain: true
            local_part_template: "{{ first_name | lower }}.{{ last_name | lower }}.{{ .random_string | trunc 10 }}"

```

results with error

```
greenmask-1  | 2025-04-17T09:47:21Z FTL cannot make a backup error="data stage dumping error: at least one worker exited with error: error processing table dump public.users: dump error: dump error on table public.users at line 1: dump error on table public.users at line 1: error evaluating when condition: unable to evaluate when condition: cannot fetch email from <nil> (1:9)\n | !(users.email endsWith('@xyz.com'))\n | ........^"
```

An example may be taken from [doc](https://docs.greenmask.io/latest/built_in_transformers/standard_transformers/random_email/)
