### ISSUE TITLE
bug: NoiseDate max/min error?

### ISSUE THREAD

**Issue by MaxenceG2M** [GreenmaskIO/greenmask#303]
Hi!

I play with playground (launched with docker compoose, version v0.2.11) and date noising, I think there is a bug on mix/max value (or my comprehension is uncorrect).

Trying to apply the [documentation example](https://docs.greenmask.io/latest/built_in_transformers/standard_transformers/noise_date/?h=noisedate#example-adding-noise-to-the-modified-date-with-dynamic-min-parameter-with-hash-engine) with a huge ratio:
```yaml
      transformers:
        - name: "NoiseDate"
          params:
            column: "hiredate"
            max_ratio: "100 year 2 mons 3 day 04:05:06.07"
            truncate: "month"
            max: "2020-01-01"
            engine: "hash"
          dynamic_params:
            min:
              column: "birthdate"q
              # default: "birthdate" - This documented value isn't valid anymore --> "[...] has invalid keys: default"
```
([Just add this in playground conf file](https://github.com/GreenmaskIO/greenmask/blob/4d539d6f7f6e54cac12361def814a071f710510f/playground/config.yml))

If I understand correctly:
- original date will be modified and can be ~100 year before or after
- maximal date will be 2020-01-01
- minimal date will be the birthdate

I have this kind of result:
```
$ greenmask validate --config config.yml --data --diff


        "humanresources"."employee"
+-----------+------------------+----------------+-------------------+
| %LineNum% | Column           | OriginalValue  | TransformedValue  |
+-----------+------------------+----------------+-------------------+
| 0         | birthdate        | 1969-01-29     | 1969-01-29        |
+           +------------------+----------------+-------------------+
|           | hiredate         | 2009-01-14     | 2052-05-01        |
+-----------+------------------+----------------+-------------------+
```

Another simpliest try:
```yaml
      transformers: # List of transformers to apply
        - name: "NoiseDate" # name of transformers
          params: # Transformer parameters
            max_ratio: "10 year 9 mon 1 day"
            column: "birthdate" # Column parameter - this transformer affects scheduled_departure column
            max: '2020-01-01'
            min: "1930-01-02"
```

Result:
```sh
$ greenmask validate --config config.yml --data --diff  --transformed-only


        "humanresources"."employee"
+-----------+------------------+---------------+------------------+
| %LineNum% | Column           | OriginalValue | TransformedValue |
+-----------+------------------+---------------+------------------+
| 0         | businessentityid | 1             | 1                |
+           +------------------+---------------+------------------+
|           | birthdate        | 1969-01-29    | 2020-01-01       |
+-----------+------------------+---------------+------------------+
| 1         | businessentityid | 2             | 2                |
+           +------------------+---------------+------------------+
|           | birthdate        | 1971-08-01    | 2020-01-01       |
+-----------+------------------+---------------+------------------+
[...]
All date are at the maximal value
```

I have a misundestending of the documentation, or this is a real bug?
