### ISSUE TITLE
Json transform with value_template does not work

### ISSUE THREAD

**Issue by janmeier** [GreenmaskIO/greenmask#4]
Hi - First of all, this looks like an awesome tool! Especially the ability to transform nested JSON objects.

However, I'm encountering an issue when trying to use a `value_template` with the `set` operation.

Here is the relevant part of my config:
```yaml
    - schema: "public"
      name: "fitness_package_temp"
      transformers:
        - name: "Json"
          params:
            column: "profile_data"
            operations:
              - operation: "set"
                path: "weigdddht"
                error_not_exists: true
                value_template: \"test\"
```
No matter what value template I put in, the column is set to `null`. I also tried setting `error_not_exists: true` and using a key that doesn't exist, but no error is raised

**Comment by wwoytenko** [comment]
Hi @janmeier. Thank you for the pleasant words we are happy to hear them)

Let me have a few minutes for the investigation. I will get back to you shortly.

**Comment by wwoytenko** [comment]
It found out that it was a bug. We have just fixed it. A new release will be published in a few hours

**Comment by wwoytenko** [comment]
We have just pushed a fix. So for now it has to work as expected. A new release will be available in a few minutes.

I have tested it with the next config

```yaml
- schema: "public"
  name: "test"
  transformers:
    - name: "Json"
      params:
        column: "data"
        operations:
          - operation: "set"
            path: "weigdddht"
            value_template: >
              {{- .GetOriginalValue | add 100 -}}
```

The result is below:

<img width="325" alt="image" src="https://github.com/GreenmaskIO/greenmask/assets/74241416/2ca36679-e109-4074-801b-84142f9b2ab8">

@janmeier Thank you so much for reporting an issue.
