### ISSUE TITLE
Hash transformer is too slow

### ISSUE THREAD

**Issue by viniciuschiele** [GreenmaskIO/greenmask#8]
I'm currently using `RandomUuid` for most of the columns but I was asked to hash the original values to maintain the same masked value.

I've replaced `RandomUuid` with `Hash` and what used to take less than a minute to dump/transform the data now takes 30 min.

This is what looks like the `transformation` config for 6 tables
```
    - schema: core
      name: users
      transformers:
        - name: Hash
          params:
            column: email
        - name: Hash
          params:
            column: first_name
        - name: Hash
          params:
            column: last_name
```

**Comment by wwoytenko** [comment]
We will review the implementation. But I suspect it is due to the hash function. I think we should provide hash function choice and hash function params. We will try to resolve it in the next release.

For now, I can suggest a temporal solution. You can use a simple shell script to implement any hashing function. For instance

```shell
#!/bin/bash

while read line
do
   printf "%s" "$line" | md5sum | awk '{print $1}'
done
```

And  the config can be like:

```yaml
    - schema: "humanresources"
      name: "employee"
      transformers:
        - name: "Cmd"
          params:
            driver:
              name: "text"
            expected_exit_code: -1
            skip_on_null_input: true
            executable: "/var/lib/playground/test.sh"
            columns:
              - name: "jobtitle"
```

The result

<img width="787" alt="image" src="https://github.com/GreenmaskIO/greenmask/assets/74241416/0bf52d3f-3ad0-420b-b50e-21923532178e">



Read about [Cmd transformer](https://greenmask.io/built_in_transformers/cmd/)
